akhq:
  connections:
    docker-kafka-server:
      properties:
        bootstrap.servers: "kafka-1:9092,kafka-2:9092,kafka-3:9092"
      schema-registry:
        url: "http://schema-registry:8081"
      connect:
        - name: connect
          url: "http://kafka-connect:8083"